"""BusinessOS identity foundation public surface."""

from .authority import lock_membership_for_authority
from .contracts import (
    ActiveScopeSelection,
    AuthenticationSessionRecord,
    AuthenticationStrength,
    BreakGlassCredentialValidator,
    IdentityContract,
    MembershipRecord,
    MembershipStatus,
    PrincipalIdentity,
    SAMLAssertionValidator,
)
from .module import (
    AuthenticationSessionRevoked,
    AuthenticationSessionStarted,
    ConfigureOIDCProvider,
    CreateUser,
    GetAuthenticationSession,
    GetMembership,
    GrantMembership,
    IdentityModule,
    MapExternalIdentity,
    MembershipGranted,
    MembershipRevoked,
    RegisterDevice,
    RegisterServiceAccount,
    RevokeAuthenticationSession,
    RevokeMembership,
    SetMFAPolicy,
    StartAuthenticationSession,
    ValidateAuthenticationSession,
)
from .oidc import (
    OIDCConfiguration,
    OIDCContextResolver,
    OIDCTokenVerifier,
    RemoteJWKSetResolver,
    SigningKeyResolver,
    VerifiedOIDCClaims,
)

__all__ = [
    "ActiveScopeSelection",
    "AuthenticationSessionRecord",
    "AuthenticationSessionRevoked",
    "AuthenticationSessionStarted",
    "AuthenticationStrength",
    "BreakGlassCredentialValidator",
    "ConfigureOIDCProvider",
    "CreateUser",
    "GetAuthenticationSession",
    "GetMembership",
    "GrantMembership",
    "IdentityContract",
    "IdentityModule",
    "MapExternalIdentity",
    "MembershipGranted",
    "MembershipRecord",
    "MembershipRevoked",
    "MembershipStatus",
    "OIDCConfiguration",
    "OIDCContextResolver",
    "OIDCTokenVerifier",
    "PrincipalIdentity",
    "RegisterDevice",
    "RegisterServiceAccount",
    "RemoteJWKSetResolver",
    "RevokeAuthenticationSession",
    "RevokeMembership",
    "SAMLAssertionValidator",
    "SetMFAPolicy",
    "SigningKeyResolver",
    "StartAuthenticationSession",
    "ValidateAuthenticationSession",
    "VerifiedOIDCClaims",
    "lock_membership_for_authority",
]
